### ISSUE TITLE
在测试网上跑起来，打开页面并没有笔记列表

### ISSUE THREAD

**Issue by NanQi** [kenspirit/secret-note#1]
右边的Secrets Kept一直为空，在Rinkeby测试，没有在主网测试。

**Comment by kenspirit** [comment]
@NanQi 我本地测试没有问题啊。

你怎么测试的？

如果你要本地跑起来，要改几个地方。因为 master 分支我现在直接拿来用做 github pages 了。

1. 改根目录下的 index.html 那些 JS 脚本引用为
`<script type="text/javascript" src="/dist/build.js"></script>`

2. 把 `dist` 目录下的 `index.html` 删除了

3. 把 `App.vue` 里面的 RINKEBY Testnet 那部分注释打开，Mainnet 的注释了。

**Comment by NanQi** [comment]
我build以后直接执行npm run dev，存储支持什么的都没问题，就是笔记列表没有显示出来。
我看你noteAccount是从localstorage中读取的，我这里并没有存进去。
我clone你的master分支，App.vue里的Rinkeby配置已经修改了，要在测试网跑还需要怎么做？
能使用ganache测试么？

**Comment by kenspirit** [comment]
@NanQi 自己测试的话，不用 build。直接 npm run dev 就可以了。你如果用 ganache 的话，应该要在 MetaMask 设置自定义的网络，并且要在 ganache 部署那个 contract，用自己的 contract 地址。

连去哪个帐号，哪个网络，还有保存笔记时候，发到哪个合约的地址，你都可以从交易提示看到的。

**Comment by NanQi** [comment]
我如果直接运行npm run dev，运行的js文件仍然是dist里面的，合约地址是主网的，我修改成Rinkeby配置，必须build以后，再运行npm run dev才可以跑起来。
现在我的问题是save操作没问题，但是Secrets Kept并没有显示出来。

**Comment by kenspirit** [comment]
@NanQi 我这边测试过是可以收到通知，并显示在 Secret Kept 上面的。不知道你说的 save 操作成功是指什么。因为要收到通知，必须是 ETH trx 确认过后，还要再等一会。你要确认 MetaMask 上的保存 transaction 是不是发到正确的合约地址，已经经 Testnet 确认。
